/*
 * generated by Xtext
 */
package org.protelis.parser.ui.contentassist

import org.protelis.parser.ui.contentassist.AbstractProtelisProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ProtelisProposalProvider extends AbstractProtelisProposalProvider {
}
