/*
 * generated by Xtext 2.10.0
 */
package org.protelis.parser.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ProtelisIdeaModule extends AbstractProtelisIdeaModule {
}
