/*
 * generated by Xtext 2.15.0
 */
package org.protelis.parser.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ProtelisWebModule extends AbstractProtelisWebModule {
}
