/*
 * generated by Xtext
 */
package it.unibo.alchemist.language.protelis.ui.contentassist

import it.unibo.alchemist.language.protelis.ui.contentassist.AbstractProtelisProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ProtelisProposalProvider extends AbstractProtelisProposalProvider {
}
