/*
 * generated by Xtext 2.15.0
 */
package org.protelis.parser


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProtelisStandaloneSetup extends ProtelisStandaloneSetupGenerated {

	def static void doSetup() {
		new ProtelisStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
