/*
 * generated by Xtext 2.10.0
 */
package org.protelis.parser.idea.lang


class ProtelisFileType extends AbstractProtelisFileType {
	public static final ProtelisFileType INSTANCE = new ProtelisFileType()
	
	new() {
		super(ProtelisLanguage.INSTANCE)
	}
}
