/*
 * generated by Xtext
 */
package org.protelis.parser.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ProtelisUiModule extends AbstractProtelisUiModule {
}
