name: CI
on:
  push:
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 17]
        distribution: [adopt]
    concurrency:
      group: ${{ github.workflow }}-build-${{ matrix.os }}-${{ matrix.jvm_version }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}-latest
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: danysk/action-checkout@0.2.1
      - name: Remove unsupported flag on Java 8
        if: matrix.jvm_version == 8
        run: rm .mvn/jvm.config
      - uses: DanySK/build-check-deploy-gradle-action@1.2.1
        with:
          build-command: |
            mvn package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          check-command: |
            mvn test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          deploy-command: |
            if [ -n "$SIGNING_KEY" ]; then
              echo "$SIGNING_KEY" > key.asc
              gpg --import key.asc
              rm key.asc
            fi
            mvn deploy -B -Dmaven.test.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          java-version: ${{ matrix.jvm_version }}
          should-run-codecov: false
          should-deploy: ${{ matrix.jvm_version == 8 && matrix.os == 'ubuntu' }}
          should-validate-wrapper: false
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
