name: CI
on:
  push:
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 17]
        distribution: [adopt]
    concurrency:
      group: ${{ github.workflow }}-build-${{ matrix.os }}-${{ matrix.jvm_version }}-${{ github.event.number || github.ref }}
    runs-on: ${{ matrix.os }}-latest
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: danysk/action-checkout@0.2.1
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Checkout the update site
        if: matrix.jvm_version == 8 && matrix.os == 'ubuntu'
        uses: actions/checkout@v3.0.2
        with:
          path: update-site
          fetch-depth: 0
          persist-credentials: true
          repository: Protelis/update-site
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Remove unsupported flag on Java 8
        if: matrix.jvm_version == 8
        run: rm .mvn/jvm.config
      - uses: DanySK/build-check-deploy-gradle-action@1.2.13
        with:
          build-command: |
            mvn package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -q
          check-command: |
            mvn test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -q
          deploy-command: |
            echo '${{ secrets.SIGNING_KEY }}' > key.asc
            gpg --import key.asc
            rm key.asc
            mvn deploy nexus-staging:drop -B -Dmaven.test.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -q
            npm install
            npx semantic-release
          java-version: ${{ matrix.jvm_version }}
          should-run-codecov: false
          should-deploy: ${{ matrix.jvm_version == 8 && matrix.os == 'ubuntu' }}
          should-validate-wrapper: false
          github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
